[package]
name = "md5mobile"
version = "0.2.0"
authors = ["herman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.6.1"
console = "0.8.0"
hex = "0.3.2"
num_cpus = "1.10.1"