[package]
name = "md5mobile"
version = "0.1.0"
authors = ["herman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.6.1"